### ISSUE TITLE
bug修复

### ISSUE THREAD

**Issue by Acappellia** [NyaaCat/InfiniteInfernal#2]
- [x] beam技能导致卡服(可能是打的过远导致的)
- [x] potionself、potionhit技能不生效
- [x] summon 药水云不生效
- [x] 传送技能不生效
- [x] 绝望之门粒子效果不正确
- [x] 怪物死亡爆炸会破坏地形
- [x] 间隔三秒钟的技能施放会失败
- [x] 怪物会以创造模式/观察者模式的玩家为目标
- [x] 观察者模式下四周会生怪

tbc

**Comment by ReinWD** [comment]
- beam技能现在将进行区块是否加载的判断，若区块未加载将继续飞行但不生成粒子也不判断是否命中物体（不进行反弹以及撞墙判断）
- potionself ，teleport 理论上不应存在问题
- summon 药水云 的主要问题在于NBT标签不合法，下面是报错
```
[19:47:43] [Server thread/WARN]: Couldn't load custom particle dust
com.mojang.brigadier.exceptions.CommandSyntaxException: Expected ' ' at position 4: dust<--[HERE]
```
- 绝望之门粒子效果现在的配置为：
```
//警告
 location.getWorld().spawnParticle(Particle.END_ROD, location, 100, 0, 0, 0, 0.01, null, true);
        location.getWorld().spawnParticle(Particle.PORTAL, location, 200, 0, 0, 0, 2, null, true);

//爆炸
        location.getWorld().spawnParticle(Particle.FLAME, location, 50, 0, 0, 0, 1, null, false);
        location.getWorld().spawnParticle(Particle.DRAGON_BREATH, location, 100, 0, 0, 0, 1, null, false);
```
与实际需求差距在于警告粒子实现方式略有不同。

- 间隔三秒钟的技能释放失败原因未知

**Comment by Acappellia** [comment]
potionself和teleport失效可能和技能施放失败有关 我今天再详细测试下怪物

**Comment by phoenixlzx** [comment]
1. beam 卡服务器不仅没有修复，反而更卡了。
2. 禁刷怪区仍然会刷怪，玩家站在禁刷怪区也会被仇恨锁到。
3. summon 药水云的命令在原版执行是没有问题的。
4. 很多主动和被动技能仍然无法正确触发。

**Comment by Acappellia** [comment]
1. beam变得不可见了
2. projectile技能的interval失效，已知smallfireball、shulkerbullet都只能造成原版伤害，不排除其它projectile类型（arrow类型正常）
3. 小白普通攻击、三叉戟溺尸、雪蛤等使用远程攻击的怪物，普通攻击只有原版伤害
4. teleporttoplayer技能正常
5. fire技能应为被动技能

**Comment by ObjectOrientedRem** [comment]
1. 怪物会刷新在地底直接窒息死亡
2. potionhit 效果无效

**Comment by Acappellia** [comment]
shulkerbullet只有原版伤害

**Comment by Acappellia** [comment]
为所有abilityset添加trigger。每次触发技能时只从符合trigger的ablityset中随机选择一个set。trigger包括：

SPAWN_TELEPORT
ACTIVE
HIT
HURT
DEATH
NEAR_DEATH

**Comment by Acappellia** [comment]
今日份报告：
1. 吸血技能不生效、
2. 复活技能的粒子效果需要修改
3. 为反伤技能添加声音提示

**Comment by phoenixlzx** [comment]
补充：

1. 复活技能的粒子速度提高、粒子数量减少并持续播放1sec
2. 修复 clearEffect 的问题
3. UltraStrike 技能特效（群内
4. 生物死亡仍会继续 burst 发射箭或 beam
5. ParticleShield 触发 20 tick 内没有反伤只有防御，20 tick 后再开始反伤，并且反伤有瞬发粒子特效

**Comment by ReinWD** [comment]
- [x] 修复 clearEffect 的问题?
- [x] 小白普通攻击、三叉戟溺尸、雪蛤等使用远程攻击的怪物，普通攻击只有原版伤害?
- [x] 生物死亡仍会继续 burst 发射箭或 beam
- [x] 怪物会刷新在地底直接窒息死亡
- [x] 怪物会以创造模式/观察者模式的玩家为目标

**Comment by Acappellia** [comment]
- [x] 吸血的粒子飞行速度过慢……
- [x] 区域刷怪会无视距离的等级 EDIT: 需要给 region 加参数是否按等级刷怪
- [x] 怪物的刷新范围应为一个球体，在刷新时应该确保怪物站在地面，并且有足够大的空间使怪物不窒息。对于幻翼、溺尸、守卫者等不在地面刷新的怪物应作特殊处理

**Comment by ReinWD** [comment]
- AbilityProjectile不再使用独立的chance控制触发几率，需要移除相应的配置项onPlayerAttackChance与perCycleChance
- 修复了生物死后仍然会Burst的问题
- 目前的吸血粒子使用（beam到mob距离/mob到受害者距离）^6 * (-18)+20 计算其速度。修改为（距离系数）^4 *（-15）+ 30
WIP

**Comment by ReinWD** [comment]
done
